### ISSUE TITLE
A request for finetune code about MiniCheck-FT5

### ISSUE THREAD

**Issue by lifelsl** [Liyan06/MiniCheck#2]
I tried to follow the approach of MiniCheck-FT5 in the paper a few days ago, but unfortunately, it did not achieve the same good effect🤣. I also understand that this is because my finetune code was not written very well. It is not a simple text classification task. If it's convenient for you, could you please send me the finetune code  of the MiniCheck-FT5.

**Comment by Liyan06** [comment]
Hi,

You can double check the "Appendix G Training Details" in the paper to make sure you train the model the same way as we did. 

For fine-tuning:
* You can take a look [here](https://huggingface.co/docs/transformers/model_doc/t5#resources) for fine-tuning the T5 model.
* For fine-tuning RoBERTa and DeBERTa models, we used the training script from [here](https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_classification.py).

**Comment by Liyan06** [comment]
Hi,

You can double check the "Appendix G Training Details" in the paper to make sure you train the model the same way as we did.

For fine-tuning:

* You can take a look [here](https://huggingface.co/docs/transformers/model_doc/t5#resources) for fine-tuning the T5 model.
* For fine-tuning RoBERTa and DeBERTa models, we used the training script from [here](https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_classification.py).
