### ISSUE TITLE
Generation of "claims"

### ISSUE THREAD

**Issue by yiqingxyq** [Liyan06/MiniCheck#3]
Hi!

How did you generate the claims in the benchmark? Did you (1) directly prompt the model to generate a claim, (2) first generate model responses and then decompose them into claims, and (3) use other ways?

Thanks!

**Comment by Liyan06** [comment]
Hi Yiqing,

The claims and documents from the benchmark are collected from the previous work:

- AggreFact-CNN (SOTA set, [Tang et al., 2023](https://aclanthology.org/2023.acl-long.650.pdf))
- AggreFact-XSum (SOTA set, [Tang et al., 2023](https://aclanthology.org/2023.acl-long.650.pdf))
- TofuEval-MediaSum ([Tang et al., 2024](https://arxiv.org/pdf/2402.13249.pdf))
- TofuEval-MeetingBank ([Tang et al., 2024](https://arxiv.org/pdf/2402.13249.pdf))
- Wice ([Kamoi et al., 2023](https://aclanthology.org/2023.emnlp-main.470.pdf))
- Reveal ([Jacovi et al., 2024](https://arxiv.org/pdf/2402.00559.pdf))
- ClaimVerify ([Liu et al., 2023)](https://aclanthology.org/2023.findings-emnlp.467.pdf)
- FactCheck-GPT ([Wang et al., 2023](https://arxiv.org/pdf/2311.09000.pdf))
- ExpertQA ([Malaviya et al., 2024](https://arxiv.org/pdf/2309.07852.pdf))
- Lfqa ([Chen et al., 2023](https://arxiv.org/pdf/2310.12150.pdf))

You can find more detailed description of each dataset in Appendix C of [our work](https://arxiv.org/pdf/2404.10774).

We are planning to include one additional dataset into the benchmark in a week or so. Stay tuned!
