### ISSUE TITLE
How to enable GPU usage

### ISSUE THREAD

**Issue by SarahHaKG** [Liyan06/MiniCheck#7]
Before MiniCheck(model_name='roberta-large', cache_dir='./ckpts') has a parameter called device. Now this is no longer available.

**Comment by Liyan06** [comment]
Hi,

You can add the following lines at the beginning of your code for setting GPU:
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```

Or you can use the `export CUDA_VISIBLE_DEVICES=0`  command in the terminal before running your script.

Let me know if this works for you!

**Comment by Liyan06** [comment]
You can also check the `MiniCheck Model Evaluation Demo` section in the README:

```python
from minicheck.minicheck import MiniCheck
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  

doc = "A group of students gather in the school library to study for their upcoming final exams."
claim_1 = "The students are preparing for an examination."
claim_2 = "The students are on vacation."

scorer = MiniCheck(model_name='roberta-large', cache_dir='./ckpts')
pred_label, raw_prob, _, _ = scorer.score(docs=[doc, doc], claims=[claim_1, claim_2])
```

**Comment by SarahHaKG** [comment]
> Hi,
> 
> You can add the following lines at the beginning of your code for setting GPU:
> 
> ```python
> import os
> os.environ["CUDA_VISIBLE_DEVICES"] = "0"
> ```
> 
> Or you can use the `export CUDA_VISIBLE_DEVICES=0` command in the terminal before running your script.
> 
> Let me know if this works for you!

Hi. This worked for me after I install  accelerate. Thanks.
